title: David Konzelmann
tagline: Your sidekick in using GitHub Pages and blogs
description: Klangkunst und künstlerische Fotografie
github:
  is_project_page: false
tags:
  - Soundart
  - Photography
  - Klangkunst
  - Fotografie
  - Künstler
  - Kunst
  - Saarbrücken
  - Saarland
theme: jekyll-theme-minimal
